server:
  port: 1030

spring:
  application:
    name: stock-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smc?serverTimezone=GMT
    username: root
    password: passw0rd
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:1000/eureka
    healthcheck:
      enabled: true